#!/bin/bash
# TODO: use https://github.com/Homebrew/homebrew-bundle for macos

SYSTEM_TYPE=$(uname -s)

# INSTALL DEPENDENCIES
echo "installing dependencies"
if [ "$SYSTEM_TYPE" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
      BREW_URL = 'https://raw.githubusercontent.com/Homebrew/install/master/install'
      echo ">>> Installing homebrew.."
      echo | /usr/bin/ruby -e "$(curl -fsSL $BREW_URL)" > /dev/null
    fi

    brew tap homebrew/cask-fonts  
    brew tap homebrew/cask-drivers
    brew install
      \ neovim git ripgrep fd tmux yarn htop wget docker gnupg docker-compose
      \ python rbenv ruby-build rbenv-aliases rbenv-default-gems rbenv-use reattach-to-user-namespace

elif [ "$SYSTEM_TYPE" = "Linux" ]; then
  if command -v yay >/dev/null 2>&1; then
    sudo pacman -S yay --noconfirm --needed
  fi

  yay -S zsh xclip python-neovim neovim git ripgrep fd \
    tmux python-pip openssh yarn htop wget docker docker-compose tlp \
      rbenv ruby-build rbenv-aliases rbenv-default-gems rbenv-use \
      pulseaudio-modules-bt-git --noconfirm --needed
fi

# ZSH
# Set zsh as default shell
chsh -s $(which zsh)
# Install zim framework
if [ `ls -A ~/.zim/ | wc -m` == "0" ]; then
  echo "bootstraping ZSH"
  chsh -s /usr/bin/zsh
  git clone --recursive https://github.com/zimfw/zimfw.git ~/.zim
fi

# Install tmux  plugins
if [ `ls -A ~/.tmux/plugins/tpm | wc -m` == "0" ]; then
  echo "bootstraping tmux"
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && \
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
fi

# Install neovim plugins
if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping NeoVim"

  sudo pip2 install neovim
  sudo pip3 install pynvim
  sudo yarn global add neovim

  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && \
    nvim '+PlugUpdate!' '+PlugClean!' '+qall'
fi

# JS dependencies
sudo yarn global add eslint stylelint prettier javascript-typescript-langserver

# Basic desktop apps
read -r -p "Install Basic Desktop apps? [y/N] " response
response=${response,,}
if [[ "$response" =~ ^(yes|y)$ ]]; then
  if [ "$SYSTEM_TYPE" = "Darwin" ]; then
    brew cask install \
      iterm2 slack google-chrome firefox rectangle maccy appcleaner \
      google-backup-and-sync itsycal keka notion \
      visual-studio-code disk-inventory-x

  elif [ "$SYSTEM_TYPE" = "Linux" ]; then
    yay -S \
       notion-app slack-desktop nerd-fonts-iosevka noto-fonts ttf-joypixels \
       firefox google-chrome pavucontrol alacritty \
       --noconfirm --needed
  fi
fi

read -r -p "Install Extra packages? [y/N] " response
response=${response,,}
if [[ "$response" =~ ^(yes|y)$ ]]; then
  if [ "$SYSTEM_TYPE" = "Darwin" ]; then
    brew cask install \
    android-platform-tools calibre dbeaver-community postman todoist \
    bitwarden iina libreoffice spotify transmission zoom beardedspice figma \
    logitech-options watchman
  elif [ "$SYSTEM_TYPE" = "Linux" ]; then
    yay -S \
      android-tools calibre darktable geeqie dbeaver pinta \
      rapid-photo-downloader spotify transmission-gtk zoom bitwarden \
      figma-linux postman-bin \
      --noconfirm --needed
  fi
fi

if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  sh ./macos.sh
fi

if [ "$SYSTEM_TYPE" = "Linux" ]; then
  sh ./manjaro-linux.sh
fi
