#!/bin/bash
# TODO: use https://github.com/Homebrew/homebrew-bundle for macos

SYSTEM_TYPE=$(uname -s)
COMMON_PACKAGES=(
	"docker",
	"docker-compose",
	"fd",
	"git",
	"htop",
	"neovim",
	"tmux",
	"wget",
	"yarn",
	"go",
	"rbenv",
	"rbenv-aliases",
	"rbenv-default-gems",
	"rbenv-use",
	"ripgrep",
	"ruby-build",
	"python",
	"starship",
)

# INSTALL DEPENDENCIES
echo "installing dependencies"
if [ "$SYSTEM_TYPE" = "Darwin" ]; then
		BREW_PACKAGES=("gnupg", "b4b4r07/tap/gomi")
    if ! command -v brew >/dev/null 2>&1; then
      BREW_URL = 'https://raw.githubusercontent.com/Homebrew/install/master/install'
      echo ">>> Installing homebrew.."
      echo | /usr/bin/ruby -e "$(curl -fsSL $BREW_URL)" > /dev/null
    fi
    brew tap homebrew/cask-fonts  
    brew tap homebrew/cask-drivers
		brew install (${COMMON_PACKAGES[@]} ${BREW_PACKAGES[@]})
elif [ "$SYSTEM_TYPE" = "Linux" ]; then
	PACMAN_PACKAGES=("openssh", "pulseaudio-modules-bt-git", "python-pip", "tlp", "xclip", "gomi")
  if command -v yay >/dev/null 2>&1; then
    sudo pacman -S yay --noconfirm --needed
  fi
	yay -S (${COMMON_PACKAGES[@]} ${PACMAN_PACKAGES[@]} ) --noconfirm --needed
fi

# ZSH
# Set zsh as default shell
chsh -s $(which zsh)
# Install zim framework
if [ `ls -A ~/.zim/ | wc -m` == "0" ]; then
  echo "bootstraping ZSH"
  chsh -s /usr/bin/zsh
  git clone --recursive https://github.com/zimfw/zimfw.git ~/.zim
fi

# Install tmux  plugins
if [ `ls -A ~/.tmux/plugins/tpm | wc -m` == "0" ]; then
  echo "bootstraping tmux"
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && \
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
fi

# Install neovim plugins
if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping NeoVim"

  git clone https://github.com/wbthomason/packer.nvim \
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim

  nvim '+PackerCompile' '+PackerInstall' '+qall'
  ~/.bin/install_lsp.sh
fi

# JS dependencies
sudo yarn global add eslint stylelint prettier javascript-typescript-langserver create-react-app

# Basic desktop apps
read -r -p "Install Basic Desktop apps? [y/N] " response
response=${response,,}
if [[ "$response" =~ ^(yes|y)$ ]]; then
  if [ "$SYSTEM_TYPE" = "Darwin" ]; then
    brew cask install \
      iterm2 slack google-chrome firefox rectangle maccy appcleaner \
      google-backup-and-sync itsycal keka notion \
      visual-studio-code disk-inventory-x

  elif [ "$SYSTEM_TYPE" = "Linux" ]; then
    yay -S \
       notion-app slack-desktop nerd-fonts-iosevka noto-fonts ttf-joypixels \
       firefox google-chrome pavucontrol alacritty \
       --noconfirm --needed
  fi
fi

read -r -p "Install Extra packages? [y/N] " response
response=${response,,}
if [[ "$response" =~ ^(yes|y)$ ]]; then
  if [ "$SYSTEM_TYPE" = "Darwin" ]; then
    brew cask install \
    android-platform-tools calibre dbeaver-community postman todoist \
    bitwarden iina libreoffice spotify transmission zoom beardedspice figma \
    logitech-options watchman
  elif [ "$SYSTEM_TYPE" = "Linux" ]; then
    yay -S \
      android-tools calibre darktable geeqie dbeaver pinta \
      rapid-photo-downloader spotify transmission-gtk zoom bitwarden \
      figma-linux postman-bin \
      --noconfirm --needed
  fi
fi

if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  sh ./macos.sh
fi

if [ "$SYSTEM_TYPE" = "Linux" ]; then
  sh ./manjaro-linux.sh
fi
