#!/bin/zsh
# System update script

SYSTEM_TYPE=$(uname -s)

# System
if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  # Homebrew
  brew update && brew upgrade
elif [ "$SYSTEM_TYPE" = "Linux" ]; then
  # Pacman + Aur
  sudo pacman-mirrors --continent && yay -Syu --noconfirm
fi

# Tmux
~/.tmux/plugins/tpm/scripts/update_plugin.sh

# Neovim
nvim '+PlugUpgrade' '+PlugUpdate!' '+PlugClean!' '+qall'

# Zim
source ${ZIM_HOME}/init.zsh
zimfw update && zimfw upgrade
