#!/bin/zsh
# System update script

SYSTEM_TYPE=$(uname -s)

# System
if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  brew upgrade
  brew update
  brew autoremove
  brew cleanup --prune=all
elif [ "$SYSTEM_TYPE" = "Linux" ]; then
  sudo pacman-mirrors --continent
  yay -Syu --noconfirm
fi

# ASDF plugins
asdf plugin update --all   
# Global js packages
# (cd ~/ ; yarn upgrade)
# Global ruby packages
# (cd ~/ ; gem update)
# Tmux
~/.tmux/plugins/tpm/scripts/update_plugin.sh
# Neovim
nvim --headless +PackerCompile +PackerSync +q
# Zim (zsh)
source ${ZIM_HOME}/init.zsh
zimfw update && zimfw upgrade
