#!/bin/zsh

SYSTEM_TYPE=$(uname -s)

# Update System
if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  # Homebrew
  brew update && brew upgrade && brew upgrade --cask
elif [ "$SYSTEM_TYPE" = "Linux" ]; then
  # Pacman + Aur
  yay -Syu --noconfirm
fi

# Tmux
~/.tmux/plugins/tpm/scripts/update_plugin.sh

# Neovim
nvim '+PlugUpgrade' '+PlugUpdate' '+PlugClean!' '+CocUpdate!' '+qall'

# Zim
# Duplicated from zshrc
source ${ZIM_HOME}/init.zsh
zimfw update && zimfw upgrade
